sudo: required
services:
  - docker

before_install:
  - docker build -t devpaing/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run devpaing/react-test npm test -- --coverage

after_success:
  - docker build -t devpaing/multi-client ./client
  - docker build -t devpaing/multi-nginx ./nginx
  - docker build -t devpaing/multi-server ./server
  - docker build -t devpaing/multi-worker ./worker
  #Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push docker images to docker hub
  - docker push devpaing/multi-client
  - docker push devpaing/multi-nginx
  - docker push devpaing/multi-server
  - docker push devpaing/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-290300608757"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"